name = "tvbox-source-registry-v8"
main = "src/worker.mjs"
compatibility_date = "2024-11-01"
workers_dev = true
preview_urls = true

[[kv_namespaces]]
binding = "SOURCE_HEALTH"
id = "17fb49c03c994650968ed5441d70c77e"

[triggers]
crons = ["*/5 * * * *"]
